description: >
  This is a sample executor using Docker and Node.
docker:
  - image: kieranosgood/update-git-tags-orb:0.0.1
    auth:
      username: kieranosgood
      password: $DOCKERHUB_PASSWORD  # or project environment variable reference
